Plugins: Close reader after format exception in Importer
ome/bioformats pull request #3868
Opened 2022-08-25 10:27 UTC by dgault

This is in response to an issue encountered in forum thread https://forum.image.sc/t/exception-issue-when-opening-nd2-files-with-bio-formats/40462/9

When using the BFImport command in a macro, if a FormatException occurred the underlying reader was not properly closed and the file was unable to be renamed.

This will not impact any repo tests and is safe for a patch release.

2022-08-25 14:51 UTC, melissalinkert commented
Should the reader only be closed when `FormatException` is thrown, or if any exception is thrown?

2022-09-28 11:32 UTC, jburel commented
A ``try/catch/finally`` might be more suitable.

2022-09-30 10:24 UTC, dgault commented
It really is a unique case when the underlying reader has been created but throws a `FormatException` during the `setID` call. Exceptions before that point won't need to close the reader and exceptions after will be able to close the reader as normal. So this is only dealing with that 1 particular scenario of a FormatException being thrown by the setID call.

2022-09-30 15:34 UTC, melissalinkert requested changes
I understand that this is specific to the case where an exception is thrown by `setId`, and that's definitely an improvement. If an exception other than `FormatException` is thrown during `setId` though, shouldn't the reader be closed as well?

2022-10-03 15:03 UTC, melissalinkert approved these changes

2022-10-03 18:31 UTC, merged