Added MSB 12 to 16 bit conversion
ome/bioformats pull request #3913
Opened 2022-11-25 14:17 UTC by ShaquilleLouisa-LambertInstruments

Currently the LiFlimReader does not support reading msb(most significant bit) 12 to 16 bit conversion.
I have added the functionality to check if msb or lsb should be used based on the packing value, if the packing value equals msb the new msb 12 to 16 bit conversion is used.

If there are any questions please contact me: Shaquile@LambertInstruments.com

2022-11-28 15:45 UTC, dgault commented
Hi @ShaquilleLouisa-LambertInstruments, thank you for contributing this PR to the project. We have introduced a Contributor License Agreement, would you be able to sign and return the form following the instructions on https://ome-contributing.readthedocs.io/en/latest/cla.html

Also do you have any suitable sample files which could be used to test this PR with? If you need a suitable upload location for sample files then we recommend using [Zenodo](https://www.google.com/search?q=zenodo&oq=zeno&aqs=chrome.1.69i57j69i59j46i433i512j46i175i199i512j0i433i512j46i131i175i199i433i512j69i65l2.2345j0j7&sourceid=chrome&ie=UTF-8)

2022-11-29 10:07 UTC, ShaquilleLouisa-LambertInstruments commented
This PR can be tested with the following files:
https://drive.google.com/file/d/1VWsavXPDpeA5JkMKatKmbtVaFHakkqE6/view?usp=share_link
https://drive.google.com/file/d/1iOyms_e0NWJpmAYIOFc6UN24OE0dOWnJ/view?usp=share_link

The first file is a recording with msb packing and the second file is a recording with lsb packing. The msb 12 to 16 bit conversion has been added to support opening the first file in fiji using bioformats. This can be tested by opening both files in fiji and confirming that the images look similar. The sample recordings are very dark, but that's not a problem. Without this additional conversion this wasn't possible, the opening of a msb packed recording resulted in vertical white lines in the image.

2022-11-29 10:11 UTC, ShaquilleLouisa-LambertInstruments commented
Hi @dgault Thank you for looking into this PR, I have signed the Contributor License Agreement and shared the sample files in my previous comment.

2022-12-01 10:15 UTC, dgault commented
Thanks @ShaquilleLouisa-LambertInstruments, I have marked the PR for inclusion in our CI and nightly repository tests. If they remain green we will aim to get this PR reviewed in the next few days.

2022-12-13 16:38 UTC, dgault requested changes
Hi @ShaquilleLouisa-LambertInstruments, thank you again for submitting the contribution. 

Overall the addition of support for MSB packing looks solid, I noticed when testing that some of the pixels values for the LSB sample had been unexpectedly changed. I believe this was due to bit operations being carried out on signed bytes, I have added some suggested changes which should resolve this. 

Also, the sample files provided are using a `flc` extension while currently the reader only recognises `fli`. If you want to add support for the flc extension also then the constructor can be updated to use the below:
`super("LI-FLIM", new String[] {"fli", "flc"});`

2022-12-13 16:38 UTC, dgault commented on components/formats-gpl/src/loci/formats/in/LiFlimReader.java
> +      image16[idx16 + 3] = (byte)((image[idx + 2]) >> 4);
```suggestion
      image16[idx16] = (byte)(image[idx] & 0xff);
      image16[idx16 + 1] = (byte)((image[idx + 1] & 0x0f));
      image16[idx16 + 2] = (byte)(((image[idx + 1] & 0xf0) >> 4) | ((image[idx + 2] & 0x0f) << 4));
      image16[idx16 + 3] = (byte)((image[idx + 2] & 0xf0) >> 4);
```

2022-12-14 13:29 UTC, ShaquilleLouisa-LambertInstruments commented
Hi @dgault, thank you for reviewing my PR.

I have commited the suggested changes, but I'm a bit confused as to why the files that I shared did not have the fli extension. Are you sure they are not .fli files?

2023-01-05 18:07 UTC, dgault commented
Just catching up with this PR again after the holidays, thanks you for the extra commits. I checked the link for the sample files again, indeed they do appear to be using the fli extension, though when I click download it automatically saves them as flc for some reason. Simply renaming the extension works as expected though.

2023-01-18 13:11 UTC, ShaquilleLouisa-LambertInstruments commented
Hi @dgault, since there are no longer any problems with this PR and all automatic checks have been passed 
can my PR now be merged?

2023-01-18 16:32 UTC, dgault commented
Hi @ShaquilleLouisa-LambertInstruments, I had re-tested the PR last week and was happy with the results. I then configured the sample files you provided and added them to our nightly repository tests. Those tests then failed due to the files not being closed properly and open file handles detected. (https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-folder/224415/console). This isn't related to your changes but was an issue with the existing code, it seems this was the first time it had been tested as part of our CI with 12 bit packed data. I have made a suggested code change which should resolve the issue and close the file handles as expected. Would you be OK with also including this change as part of this PR?

2023-01-19 10:44 UTC, ShaquilleLouisa-LambertInstruments commented
Hi @dgault, Thank you for looking into my PR again. I don't mind adding the requested code change you mentioned but I don't see any new requested code changes.

2023-01-19 13:53 UTC, dgault commented
Thanks @ShaquilleLouisa-LambertInstruments, with that one last suggested change we should be good to get this merged.

2023-01-24 08:13 UTC, ShaquilleLouisa-LambertInstruments commented
Sounds good, can this now get merged?

2023-01-24 10:41 UTC, dgault commented
All the builds and test are now green with this PR included, looks good to merge.

2023-01-24 10:41 UTC, merged