Update top-level Git mailmap to normalize commit author variants
ome/bioformats pull request #4026
Opened 2023-06-22 20:43 UTC by sbesson

These updates aim to associate all commits from the same contributor to a single "First Name Last Name <email>" author line. The University of Dundee or the Glencoe Software email address are used as the canonical address for current employees of these institutions. For contributors with an executed CLA, the email address specified in the  CLA is used as the canonical one.

See also https://github.com/ome/openmicroscopy/pull/6349. To review this PR, `git shortlog -se` should give you the list of normalized contributors.

2023-06-22 22:23 UTC, melissalinkert requested changes
Few typos as noted, otherwise looks like these are missing:

```
2  Aaron Avery <aaron@Aarons-MacBook-Pro.local>
1  JulyChen728 <602114946@qq.com>
3  LambertJohan <45658761+LambertJohan@users.noreply.github.com>
4  Parm0n <ilya.parm@gmail.com>
```

From https://www.openmicroscopy.org/contributors/ and public mailing list archives, I'd expect those to be:

- `Aaron Avery <aaron.avery@healthmyne.com>`
- https://github.com/JulyChen728
- `Johan Herz <johan@lambertinstruments.com>`
- Ilya Parmon

2023-06-22 22:23 UTC, melissalinkert commented on .mailmap
> +Andreica Eliana <e.andreica@oxinst.com>
Eliana Andreica (see https://www.openmicroscopy.org/contributors/)

2023-06-22 22:23 UTC, melissalinkert commented on .mailmap
> +Stefan Wagner-Conrad <stephan.wagner-conrad@zeiss.com> <46338941+swg08@users.noreply.github.com>
Stephan Wagner-Conrad

2023-06-22 22:23 UTC, melissalinkert commented on .mailmap
> +Nicholas Papp <nicola.papp@intelligent-imaging.com>
Nicola Papp

2023-06-23 08:01 UTC, sbesson commented
Thanks @melissalinkert. All suggestions/changes pushed to the exception of `JulyChen728` for which I have found no information so far.

2023-06-26 15:14 UTC, melissalinkert approved these changes

2023-06-26 15:35 UTC, dgault approved these changes

2023-06-26 15:36 UTC, merged