TiffSaver handle RGBA
ome/bioformats pull request #4059
Opened 2023-07-26 14:58 UTC by CGDogan

As I asked on https://forum.image.sc/t/bfconvert-breaks-images-with-alpha-layer-wrong-interleave/83482, bfconvert, when given 4-channel images, outputs with the monochrome tag. This means that many image decoders will try to read it as monochrome and show an invalid image. In general, we should save 4-channel images like 3-channel ones, because RGBA tagged as RGB is a supported configuration in the TIFF specification (https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf pg 77), where even the order is specified: R,G,B, then A. This will result in BioFormats producing much more compatible tiff files.

2023-07-26 15:42 UTC, melissalinkert commented
For reference, the original logic was introduced in #3057. It would help to know which viewer(s) can't handle TIFFs converted without this change, so that we can better evaluate the behavior of this change across a range of use cases.

2023-07-26 15:58 UTC, CGDogan commented
My mac can’t, but the reason I’m concerned with this is that I bfconvert images to tiff so that I can view with OpenSlide, but OpenSlide then shows it as monochrome. But for comparison, I searched for “view tiff online” and opened 5 different sites, none of them could view it.

2023-07-26 15:58 UTC, CGDogan commented
My mac can’t, but the reason I’m concerned with this is that I bfconvert images to tiff so that I can view with OpenSlide, but OpenSlide then shows it as monochrome. But for comparison, I searched for “view tiff online” and opened 5 different sites, none of them could view it.

2023-11-21 23:13 UTC, melissalinkert requested changes
Running `bfconvert` with an RGBA input file and `test.tiff` as the output file name does result in a 4-channel RGB TIFF which can be displayed with `showinf`, ImageMagick's `display`, and Windows Photos. However, `display` shows this warning:

```display-im6.q16: Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.```

The `ExtraSamples` tag should be set in this case, with a single value (likely 0). See pages 31-32 of the TIFF specification.

2023-11-22 17:54 UTC, CGDogan commented
It should work now?

2023-11-22 18:24 UTC, melissalinkert requested changes

2023-11-22 18:24 UTC, melissalinkert commented on components/formats-bsd/src/loci/formats/tiff/TiffSaver.java
> +          int[] extraSamplesArray = {1};
I don't think it's safe to assume here that the 4th channel is always what the TIFF specification refers to as "associated alpha data", which is what the `1` here indicates. That may be true in many cases, but I'm uncomfortable with this assumption for *every* 4-channel RGB input. As noted in the previous review, I think setting the `ExtraSamples` entry to 0 ("unspecified data" per the TIFF specification) is the safest option.

2023-11-22 18:24 UTC, melissalinkert commented on components/formats-bsd/src/loci/formats/tiff/TiffSaver.java
> +          int[] extraSamplesArray = {2};
As in line 1037, I am unconvinced that we can safely assume that the 4th channel is "unassociated alpha data". I would prefer to see this value changed to 0 unless there is a strong argument to the contrary.

2023-11-27 16:38 UTC, melissalinkert approved these changes
This looks fine to me now. If I convert a 4-channel RGBA PNG to TIFF with bfconvert, the resulting TIFF has the `PhotometricInterpretation`, `BitsPerSample`, and `ExtraSamples` values that are expected. Opening the file with ImageMagick's `display` command shows a correct image with no warnings.

Converting the same file with `bfconvert -separate` continues to produce 4 separate IFDs, none of which have an `ExtraSamples` tag. The `PhotometricInterpretation` in this case is 1 (`BLACK_IS_ZERO`) and `BitsPerSample` has one entry, all as expected.

2023-11-28 13:42 UTC, merged