Extend precompressed support to read DICOM and write TIFF/OME-TIFF
ome/bioformats pull request #4190
Opened 2024-05-23 20:27 UTC by melissalinkert

Opening as a draft for now, as #4181 is higher priority. This may need some updates once #4181 is merged.

I would expect basic conversions such as `bfconvert -noflat -precompressed -compression JPEG input.dcm output.ome.tiff` to work, where the input DICOM is part of a whole slide dataset. Tile sizes should be correctly picked up without being specified in the `bfconvert` options.

A few outstanding things related to this PR and #4181:

- `-precompressed` does still require the `-compression` option to be set correctly; removing that requirement could be done here
- documentation started in https://github.com/ome/bio-formats-documentation/pull/349 should be updated to include additions here and in #4181 - we may want a separate page just for this feature

/cc @fedorov, @dclunie

2024-08-13 13:01 UTC, sbesson requested changes
In the spirit of https://github.com/ome/bioformats/pull/3992 and https://github.com/ome/bioformats/pull/4181, used `CMU-1.svs` and `CMU-1.npdi` as the source files for conversion.

For both files, the `bfconvert` utility with this PR included was executed:
- using both OME-TIFF and DICOM as the target format
- using `-compression JPEG`, `-compression JPEG-2000` and `-precompressed` as the options
Additionally the two DICOM datasets generated with the JPEG and JPEG-2000 compression from CMU-1.ndpi were used as the source of a conversion from DICOM to OME-TIFF using the same three compression options as above.

| Source file               	| Target   	| Precompressed 	| Compression 	| Conversion time 	| File size 	|
|---------------------------	|----------	|---------------	|-------------	|----------------:	|-----------	|
| CMU-1.svs                 	| DICOM    	| no            	| JPEG        	| 229.057s        	| 109M      	|
| CMU-1.svs                 	| DICOM    	| no            	| JPEG-2000   	| 682.503         	| 539M      	|
| CMU-1.svs                 	| DICOM    	| yes           	|             	| 83.013s         	| 177M      	|
| CMU-1.svs                 	| OME-TIFF 	| no            	| JPEG        	| 152.064s        	| 247M      	|
| CMU-1.svs                 	| OME-TIFF 	| no            	| JPEG-2000   	| 518.381s        	| 735M      	|
| CMU-1.svs                 	| OME-TIFF 	| yes           	|             	| 27.083s         	| 176M      	|
| CMU-1.ndpi                	| DICOM    	| no            	| JPEG        	| 113.465s        	| 127M      	|
| CMU-1.ndpi                	| DICOM    	| no            	| JPEG-2000   	| 640.609s        	| 1.2G      	|
| CMU-1.ndpi                	| DICOM    	| yes           	|             	| 16.811s         	| 191M      	|
| CMU-1.ndpi                	| OME-TIFF 	| no            	| JPEG        	| 111.965s        	| 127M      	|
| CMU-1.ndpi                	| OME-TIFF 	| no            	| JPEG-2000   	| 620.038s        	| 1.3G      	|
| CMU-1.ndpi                	| OME-TIFF 	| yes           	|             	| 6.852s          	| 191M      	|
| CMU-1_0_0.dcm             	| OME-TIFF 	| no            	| JPEG        	| 137.521s        	| 127M      	|
| CMU-1_0_0.dcm             	| OME-TIFF 	| no            	| JPEG-2000   	| 1150.285s       	| 1.3G      	|
| CMU-1_0_0.dcm (JPEG)      	| OME-TIFF 	| yes           	|             	| 6.654s          	| 127M      	|
| CMU-1_0_0.dcm (JPEG-2000) 	| OME-TIFF 	| yes           	|             	| 16.244s         	| 1.2G      	|

Overall all the conversion times and sizes  are consistent with the previous measurements made during the work on reading precompressed SVS and NDPI files. The speed-up associated with the `-precompressed` flag is comparable when writing OME-TIFF and the absolute values are typically smaller.

Trying to validate the binary data in a viewer, all converted images were found to look good except for the two OME-TIFF files created from the DICOM datasets without `-precompressed` where the tiles look to be incorrectly ordered

<img width="1635" alt="Screenshot 2024-08-13 at 13 52 42" src="https://github.com/user-attachments/assets/11d29c0e-c548-4a28-a810-2de8191660dd">

Once the above is addressed, I would re-run the tests above for consistency and I would propose to carry a few additional functional tests including:
- converting to TIFF rather than OME-TIFF (small images)
- converting to other supported formats
- mixing `-precompressed` / `-compression` flags
- for TIFF/OME-TIFF, testing a few other compression flags

2024-08-13 13:01 UTC, sbesson commented on components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
> +              writer.setInterleaved(true);
Is there a reason to special case here or should we ensure that `reader.getInterleaved` returns true appropriately so that

```
writer.setInterleaved(reader.isInterleaved() && !autoscale);
```

works correctly above?

2024-08-13 13:01 UTC, sbesson commented on components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
> +      compression = getReaderCodecName();
Actually looking forward to possible handling mixed compressions, is it preferable moving forward to _not_ specify the compression as an option and leave the internal logic detect the codec?

2024-08-13 13:01 UTC, sbesson commented on components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
> +      return true;
Definitely good to see `instanceof` checks removed. Are there specific tests that should be carried out here if the target format is neither DICOM not TIFF/OME-TIFF?

2024-08-13 13:45 UTC, melissalinkert commented on components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
> +              writer.setInterleaved(true);
`SVSReader` was the particular issue here; my concern was that swapping the return value of `reader.isInterleaved` is a potentially a lot more invasive. When that value changes, what `openBytes` returns has to change, which means things like pixels hashes change, etc.

2024-08-13 13:47 UTC, melissalinkert commented on components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
> +      compression = getReaderCodecName();
That was definitely the intent - `-precompressed` on its own with no `-compression` should work, and doesn't require knowledge of the input data.

2024-08-13 14:41 UTC, melissalinkert commented
> In the spirit of #3992 and #4181, used `CMU-1.svs` and `CMU-1.npdi` as the source files for conversion.
> Trying to validate the binary data in a viewer, all converted images were found to look good except for the two OME-TIFF files created from the DICOM datasets without `-precompressed` where the tiles look to be incorrectly ordered
> 
> <img alt="Screenshot 2024-08-13 at 13 52 42" width="1635" src="https://private-user-images.githubusercontent.com/1355463/357416799-11d29c0e-c548-4a28-a810-2de8191660dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTU2MTMsIm5iZiI6MTcyMzU1NTMxMywicGF0aCI6Ii8xMzU1NDYzLzM1NzQxNjc5OS0xMWQyOWMwZS1jNTQ4LTRhMjgtYTgxMC0yZGU4MTkxNjYwZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMTMyMTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWRmMWM4YjhjMDE4YzE5MTE3ZDJlODY2MjQ3M2IyNTRhZGY3N2NmZmI2MzIwOWQwM2NmM2MzN2M1NTQxNjFmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.heQRLkD-ahz-Zfx4BsJwZK7adbazCEqkYNs4tfr1Z-0">

Currently investigating, but it looks like this issue is reproducible if the same DICOM -> OME-TIFF conversion is done with develop. It's still worth fixing here, but may not have been introduced by this PR.

2024-08-13 15:51 UTC, melissalinkert commented
I believe 29e8c05f22 fixes the scrambled tiles issue. As noted above, I could reproduce the problem both with this PR and with develop alone, using something like:

```
bfconvert -noflat -compression JPEG /path/to/cmu1_0_0.dcm cmu1.ome.tiff
```

However, specifying the tile sizes explicitly:

```
bfconvert -noflat -compression JPEG -tilex 512 -tiley 512 /path/to/cmu1_0_0.dcm cmu1.ome.tiff
```

no longer showed the problem. With 29e8c05f22, I would expect either command to result in a correct OME-TIFF.

2024-08-13 15:59 UTC, melissalinkert commented on components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
> +      return true;
See 29e8c05f22.

It's probably worth a couple of tests, maybe with fake data, for things like ICS. Keep in mind most writers do not allow tile-wise conversion at all (e.g. https://github.com/ome/bioformats/blob/develop/components/formats-bsd/src/loci/formats/out/APNGWriter.java#L84), and DICOM/TIFF/OME-TIFF are the only ones that would support pyramids.

2024-08-14 10:04 UTC, sbesson reviewed
Reproducing the tests from https://github.com/ome/bioformats/pull/4190#pullrequestreview-2234915792 with the last commit, the issue raised when converting from DICOM to OME-TIFF without precompression are now addressed 

<img width="909" alt="Screenshot 2024-08-14 at 10 59 52" src="https://github.com/user-attachments/assets/3cc8e301-1836-4dc3-9210-8cf80a2bd1c9">

Timings and file sizes are consistent with the table of the last review

2024-08-14 16:44 UTC, sbesson approved these changes
In addition to the last review, performed a few additional conversion using different input/output formats (fake, ics, tiff) with different source compression and tile/compression options.

The first set of conversion used a [fake file](https://bio-formats.readthedocs.io/en/stable/developers/generating-test-images.html) with XY dimensions 2000x2000, 10 focal points and 2 channels. All the conversions using TIFF as the source format used one of the TIFF files generated from the fake files

| Source format 	| Source compression 	| Target format 	| Precompressed 	| Target tile size 	| Target compression 	| Conversion time 	| File size 	|
|---------------	|--------------------	|---------------	|---------------	|------------------	|--------------------	|----------------:	|-----------	|
| Fake          	| Uncompressed       	| ICS           	| no            	|                  	|                    	| 1.143           	| 197M      	|
| Fake          	| Uncompressed       	| ICS           	| no            	| 512x512          	|                    	| 1.105s          	| 197M      	|
| Fake          	| Uncompressed       	| ICS           	| yes           	|                  	|                    	| Failed          	|           	|
| Fake          	| Uncompressed       	| TIFF          	| no            	|                  	| Uncompressed       	| 2.558s          	| 130M      	|
| Fake          	| Uncompressed       	| TIFF          	| no            	|                  	| zlib               	| 5.001s          	| 18M       	|
| Fake          	| Uncompressed       	| TIFF          	| no            	| 512x512          	| Uncompressed       	| 3.222s          	| 81M       	|
| Fake          	| Uncompressed       	| TIFF          	| no            	| 512x512          	| zlib               	| 3.21s           	| 448K      	|
| Fake          	| Uncompressed       	| TIFF          	| no            	| 512x512          	| JPEG               	| 3.889s          	| 2.5M      	|
| Fake          	| Uncompressed       	| TIFF          	| no            	| 512x512          	| JPEG-2000          	| 7.178s          	| 448K      	|
| TIFF          	| zlib               	| ICS           	| no            	|                  	|                    	| 1.952s          	| 77M       	|
| TIFF          	| zlib               	| ICS           	| no            	| 512x512          	|                    	| 1.065s          	| 105M      	|
| TIFF          	| zlib               	| ICS           	| yes           	|                  	|                    	| 1.074s          	| 105M      	|
| TIFF          	| zlib               	| TIFF          	| no            	|                  	| Uncompressed       	| 2.436s          	| 77M       	|
| TIFF          	| zlib               	| TIFF          	| yes           	|                  	|                    	| failed          	|           	|
| TIFF          	| zlib               	| TIFF          	| no            	| 512x512          	| JPEG               	| 3.724s          	| 2.5M      	|
| TIFF          	| JPEG               	| TIFF          	| no            	|                  	| Uncompressed       	| 2.494s          	| 77M       	|
| TIFF          	| JPEG               	| TIFF          	| yes           	|                  	|                    	| failed          	|           	|
| TIFF          	| JPEG               	| TIFF          	| no            	| 512x512          	| zlib               	| 3.26s           	| 546K      	|

The conversion with a `-precompressed` flag failed with

```
java.lang.UnsupportedOperationException: Reader does not support pre-compressed tile access
```

which I believe is the expectation.

All generated files were validated visually with all planes/tiles being available for all coordinates.

From my side this is ready for inclusion in the next Bio-Formats release. Given the nature of the changes, this is definitely not amenable for a patch release but could be included in a release incrementing the minor or major version to communicate the backwards-compatible API additions.

In terms of documentation, I can see a few follow-up tasks including:

- update the `bfconvert` utility help to list the formats/codecs supporting pre-compressed tiles like we do for compression
- update the user/technical documentation especially https://bio-formats.readthedocs.io/en/latest/users/comlinetools/conversion.html to remove the requirement to specify the compression format and list the additional reader/writers/codecs supporting the `-precompressed` flag
In the mid-term, I wonder whether we'll want to maintain a table of format/codecs that support precompressed reading in reading/writing mode separately.

2024-08-26 15:03 UTC, sbesson commented
Merging to fix conflicts with #4164 and unblock the performance work.

2024-08-26 15:03 UTC, merged