OIRReader: Major performance improvement when reading a ROI within a plane
ome/bioformats pull request #4205
Opened 2024-07-01 07:49 UTC by NicoKiaru

In the implementation before this PR each time a small ROI is read from an image, a full OIR Pixelblock was read. Combined with the fact that the Optimal Tile Size was not overriden and defaulted to a thin stripe in y (128 pixels), this could lead to a particularly bad scenario for big images:

- Imagine a 10000 by 10000 pixel plane read by tiles of 10000x128 pixels -> 79 tiles have to be read to read the full plane
- For big tiled OIR images, a PixelBlock typically spans the full plane
- This means that, to acquire all tiles of this plane, the full plane is actually read 97 times

The proposed new implementation of this PR:
- prevents reading fully all PixelBlocks when one needs to read a ROI within them
- overrides getOptimalTile size methods to match the underlying PixelBlock size (or crops at 2048 pixels)

When requesting a cropped region within big images, the speedup is massive.

Here's a real time display with big dataviewer with the current implementation:
![previousreader](https://github.com/ome/bioformats/assets/20223054/114ea211-b4ff-4eae-b4f7-de0c01ca71b2)

Here's a real time display with big dataviewer with the implementation in this PR:
![prreader](https://github.com/ome/bioformats/assets/20223054/0b262ec3-d309-4f11-8ed6-040437622fc6)

2024-07-01 10:51 UTC, dgault commented
Thanks again @NicoKiaru for the hard work investigating and getting the PR opened. I have marked it for inclusion for the repository tests to check for any side effects in other datasets.

2024-07-01 10:53 UTC, NicoKiaru commented
Thanks, I have tested it on very few files, so while I tried to keep the changes to the minimum, I'm not sure I did not break something! Let's see.

2024-07-03 11:40 UTC, jburel commented
Failed with the following error
```
setId("/data/martin/20170824_JupGFP_HisRFP_wL3_30xSI_4xzoom_0p5z_A01_G001_0001.oir") failed
   [testng] java.lang.NullPointerException: Cannot assign field "yStart" because "block" is null
   [testng] 	at loci.formats.in.OIRReader.initFile(OIRReader.java:432)
   [testng] 	at loci.formats.FormatReader.setId(FormatReader.java:1480)
```

2024-07-03 13:38 UTC, melissalinkert commented
Note that some of the test failures occur on public data:

* https://downloads.openmicroscopy.org/images/Olympus-OIR/etienne/venus%20stack.oir
* https://downloads.openmicroscopy.org/images/Olympus-OIR/etienne/amy%20slice%20z%20stack_0001.oir

2024-07-07 12:57 UTC, NicoKiaru commented
So I've fixed what I could test with the public files.

2024-07-15 15:45 UTC, dgault commented
Added a commit to fix a NullPointerException in the nightly tests (https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-folder/18844/console)

2024-07-16 12:59 UTC, dgault commented
Added a further commit to address failures in the nightly tests: https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-folder/19008/console

These last 2 failures related to spectral images using modulo C. I have updated the indexing for the blocks to match the previous behaviour.

2024-07-18 14:00 UTC, dgault commented
I am still seeing failures for the modulo C files in the nightly tests, though from testing it looks as though the original implementation currently in the reader may also be incorrect. In both cases a single set of pixel blocks is being used for each of the modulo C frames, the tests fail because this PR is defaults to a different frame.

The real issue seems to be that in the case of the Lambda files as set [here](https://github.com/ome/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/OIRReader.java#L1365-L1371), that I am unsure how to identify from the pixel block uids which index they correctly belong to. Currently both implementations are matching the channel id which is the same for each step and results in the same frames each time. I will try and dig further to see if I can correctly identify the correct blocks.

2024-07-18 14:12 UTC, NicoKiaru commented
Ok, good luck with that. If you have a public lambda file, that would be nice. But if not I can also try to create one.

2024-07-18 15:23 UTC, NicoKiaru commented
I've submitted some example file to the bio-formats QA community in Zenodo. They cover:
- lambda scan
- lambda scan + t
- lambda scan + z
- lambda scan + z + t

2024-07-19 15:43 UTC, NicoKiaru commented
I've made a small modification, which, in the files I could test, fixes the reading of spectral acquisition.

2024-08-26 08:08 UTC, NicoKiaru commented
Hello, do you think you would be able to give it a (new) go ? I've shared some sample spectral dataset + the previous version was not able to read spectral dataset from FV4000. Of course there may still be issued with private files, but I can't fix anything in that regard.

2024-09-02 14:17 UTC, melissalinkert commented
Thanks for the updates, @NicoKiaru, and apologies for the delay. This will now be included in tonight's builds, so we'll know the status in the morning.

2024-09-03 15:56 UTC, melissalinkert commented
This appears to have passed all tests (https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-folder/27045/console), so is on my list to review for inclusion in 8.0.0.

2024-09-03 19:42 UTC, NicoKiaru commented
Thanks! Before doing that please wait a day or two: I want to upload such a big 2D dataset since I'm not sure you have that in the demo files.

2024-09-04 07:21 UTC, NicoKiaru commented
Ok, I've submitted a tiled image on Zenodo bio-formats submission community.

I think to demo the performance increase I should rather have done a single very large plane than a z-stack. But timing the opening with a 'crop on import' the perf increase should still be visible I hope.

2024-09-04 07:43 UTC, joshmoore commented
see https://zenodo.org/records/13680725

2024-09-06 13:56 UTC, melissalinkert requested changes
I am generally fine with this, there are just a few small things that should be fixed before merging, the null check on line 213-214 being most important.

Several tests of `showinf -crop ...` with https://zenodo.org/records/13680725 in particular show a definite performance improvement with these changes compared to the current state of develop. I also tried reading the `matl.omp2info` (see `OlympusTileReader`); while that wasn't dramatically faster, it certainly wasn't any worse, and did demonstrate that the optimal tile size changes here are correctly propagated to `OlympusTileReader`.

As previously indicated, automated tests are passing. Since those tests don't thoroughly exercise reading cropped planes, I also ran a simple test to compare plane hashes and read times across all of our .oir data:

```
import java.security.MessageDigest;
import java.util.ArrayList;
import loci.common.DataTools;
import loci.common.DebugTools;
import loci.tests.testng.*;
import loci.formats.in.OIRReader;

public class PixTest {
  public static void main(String[] args) throws Exception {
    DebugTools.enableLogging("WARN");
    MessageDigest md = MessageDigest.getInstance("MD5");
    try (OIRReader reader = new OIRReader()) {
      ArrayList<String> testFiles = new ArrayList<String>();
      TestTools.getFiles(args[0], testFiles, new ConfigurationTree(args[0], args[1], null), null, null, "");
      for (String testFile : testFiles) {
        if (!reader.isThisType(testFile)) {
          continue;
        }
        System.out.println(testFile);
        reader.setId(testFile);

        int x = reader.getSizeX() /4;
        int y = reader.getSizeY() / 4;
        int w = (int) Math.min(reader.getSizeX() / 3, 2048);
        int h = (int) Math.min(reader.getSizeY() / 3, 2048);

        long t0 = System.currentTimeMillis();
        for (int plane=0; plane<reader.getImageCount(); plane++) {
          byte[] buf = reader.openBytes(plane, x, y, w, h);
          md.reset();
          md.update(buf);
          String md5 = DataTools.bytesToHex(md.digest());
          System.out.println("plane #" + plane + " MD5: " + md5);
        }
        long t1 = System.currentTimeMillis();
        System.out.println("total plane read time: " + (t1 - t0) + " ms");
        reader.close();
      }
    }
  }
}
```

Without this change, that test against all of our existing .oir data took 75m22s locally. With this change and the addition of a null check between lines 213/214, it takes 58m58s. There are MD5 differences for the following files, but these appear to be correct and a result of better lambda handling:

```
olympus/spectral_scan_XYL.oir
qa-17409/Stitch_A01_G001.oir
```

For both files, `showinf` with develop shows the same data for all planes, which is not the case with this change.

So, once the few suggestions here have been addressed and we have one more passing build that includes the updates, I am happy to see this merged.

2024-09-06 13:56 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/OIRReader.java
> +      cztToPixelBlocks.clear();
`optimalTileHeight` should be reset to 0 here as well, mostly for completeness.

2024-09-06 13:56 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/OIRReader.java
> +  public int getOptimalTileHeight() {
Best practice is to call `FormatTools.assertId(currentId, true, 1)` first, so that an exception is thrown if `getOptimalTileHeight()` is called on an uninitialized reader by mistake.

2024-09-06 13:56 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/OIRReader.java
> +  public int getOptimalTileWidth() {
As with `getOptimalTileHeight()` above, calling `FormatTools.assertId(currentId, true, 1)` first is consistent with how other readers implement these methods.

2024-09-06 13:56 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/OIRReader.java
> +    for (PixelBlock block : blocks) { // This list is sorted along y
There should be a null check on `block`, as elements of `blocks` may be null if fewer than the maximum number of blocks were stored for a particular plane.

2024-09-06 14:17 UTC, NicoKiaru commented
Thanks a lot @melissalinkert for this thorough review! I'll get back to it next week.

2024-09-09 08:12 UTC, NicoKiaru commented on components/formats-gpl/src/loci/formats/in/OIRReader.java
> +  public int getOptimalTileHeight() {
Done below

2024-09-09 08:12 UTC, NicoKiaru commented on components/formats-gpl/src/loci/formats/in/OIRReader.java
> +  public int getOptimalTileWidth() {
Done below

2024-09-09 08:14 UTC, NicoKiaru commented on components/formats-gpl/src/loci/formats/in/OIRReader.java
> +    for (PixelBlock block : blocks) { // This list is sorted along y
I put a warning, I hesitated to put a message like:
''' please contribute this file (id) to the OME team for investigation '''

2024-09-09 08:14 UTC, NicoKiaru commented on components/formats-gpl/src/loci/formats/in/OIRReader.java
> +      cztToPixelBlocks.clear();
ok!

2024-09-09 08:14 UTC, NicoKiaru commented
I've done the modifications you suggested. Thanks again @melissalinkert !

2024-09-09 16:22 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/OIRReader.java
> +    for (PixelBlock block : blocks) { // This list is sorted along y
I think this warning is fine as-is - we don't typically ask for files directly in warning/error messages.

2024-09-10 14:57 UTC, melissalinkert approved these changes
Merging as https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-repo/182/ and https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-repo/183/ passed with the latest changes included.

Thanks again for the work here, @NicoKiaru.

2024-09-10 14:57 UTC, merged