Add Hamamatsu DCIMG Reader
ome/bioformats pull request #4255
Opened 2024-12-02 13:30 UTC by zacsimile

I found myself in the unfortunate position of regularly needing to investigate bead stacks acquired as `.dcimg` files. My goal was to load them and reslice in xz. This seemed easiest to do in ImageJ, so I ported a merge of some existing DCIMG readers to Java for use as a local tool. The result is presented here, in case there is broader interest in the reader.

There are a few things to note:

1. On a Mac (works fine on Windows), while the stacks load fine, reslicing does not work on the loaded stack. I receive the error

```
java.lang.IllegalArgumentException: Invalid bitDepth: 0
  at ij.gui.NewImage.createImage(NewImage.java:397)
  at ij.plugin.Slicer.createOutputStack(Slicer.java:462)
  at ij.plugin.Slicer.resliceRectOrLine(Slicer.java:442)
  at ij.plugin.Slicer.reslice(Slicer.java:115)
  at ij.plugin.Slicer.run(Slicer.java:80)
  at ij.IJ.runPlugIn(IJ.java:216)
  at ij.Executer.runCommand(Executer.java:152)
  at ij.Executer.run(Executer.java:70)
  at java.lang.Thread.run(Thread.java:750)
```

If I duplicate the stack, reslicing works fine. Does anyone know what is likely to cause such an error just on a Mac?

2. I’ve made a design choice, where multiple frames within a single DCIMG file are loaded in `T` and multiple DCIMG files are loaded along `Z`. 

3. I’ve done the bare minimum on loading metadata.

4. I have only tested the 4 pixel correction on older DCIMG 0x7. I don’t have any examples of DCIMG 0x1000000 or 0x2000000 that need the 4 pixel correction, though I would be happy to take a look at one.

2024-12-03 15:33 UTC, melissalinkert commented
Thank you, @zacsimile.

Before we proceed with review, there are two things we will need:

- a signed Contributor License Agreement (see https://ome-contributing.readthedocs.io/en/latest/cla.html)
- example datasets we can use to test this reader (uploaded to https://zenodo.org/communities/bio-formats)

Once we have those two things, we'll assign reviewers to this pull request. Please note we'll do our best to review in a timely fashion, but can't guarantee a timeline at this point. Please see https://forum.image.sc/t/bio-formats-update/101734 for more information about the current state of Bio-Formats maintenance.

> 1. On a Mac (works fine on Windows), while the stacks load fine, reslicing does not work on the loaded stack. I receive the error
> 
> ```
> java.lang.IllegalArgumentException: Invalid bitDepth: 0
>   at ij.gui.NewImage.createImage(NewImage.java:397)
>   at ij.plugin.Slicer.createOutputStack(Slicer.java:462)
>   at ij.plugin.Slicer.resliceRectOrLine(Slicer.java:442)
>   at ij.plugin.Slicer.reslice(Slicer.java:115)
>   at ij.plugin.Slicer.run(Slicer.java:80)
>   at ij.IJ.runPlugIn(IJ.java:216)
>   at ij.Executer.runCommand(Executer.java:152)
>   at ij.Executer.run(Executer.java:70)
>   at java.lang.Thread.run(Thread.java:750)
> ```
> 
> If I duplicate the stack, reslicing works fine. Does anyone know what is likely to cause such an error just on a Mac?

I don't have any immediate ideas, but once we have example data I expect we would try to reproduce this error as part of the review process.

2024-12-03 15:45 UTC, melissalinkert commented
Apologies, it looks like we do already have a signed CLA. So we'll just need example data in order to proceed here.

2024-12-03 15:52 UTC, zacsimile commented
No worries! I apologize, after reading that forum post, it seems this is exactly the kind of PR you are not looking for at the moment. Thanks for having a look anyway, and please take your time. I have compiled a local version of bioformats that works for me at the moment. 

I will upload some data ASAP. I just have to email a few people because a couple of the files I tested on are not mine and I'm not sure if uploading them is OK. In this case, I will have to record a couple more files in different DCIMG formats.

2024-12-05 09:00 UTC, zacsimile commented
Please find examples for DCIMG `0x7` and `0x1000000` at https://zenodo.org/records/14281237 and https://zenodo.org/records/14268554, respectively. The first one is a stack with multiple frames in a single DCIMG file and the second is a sequence of single frames, both monochromatic. I still do not have a DCIMG version `0x2000000` or a DCIMG with multiple color channels, but I do not claim to be able to load these with the current code. Happy to update it later if someone provides one or both of these examples.

2024-12-06 09:07 UTC, zacsimile commented
Fixed 4-pixel correction for DCIMG 0x1000000 upon receiving example at https://zenodo.org/records/14287640.

2024-12-09 17:01 UTC, melissalinkert requested changes
Thanks for providing test data, @zacsimile. I've done a first round of code review - let us know when you have had a chance to address all of the comments, and then we can make a plan for further testing.

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +package loci.formats.in;
This file should have the same copyright statement that is at the top of the other readers in the `formats-gpl` component.

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +    if (!isGroupFiles() || noPixels) return null;
This will produce an invalid used files list any time file grouping turned off, even on a single-file dataset. `showinf -nogroup  Cell07_642_000_000.dcimg` demonstrates the issue. When `isGroupFiles()` is `false`, the used file list should contain the one file that is being read.

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +    return true;
These two lines could be simplified to `return desc.equals("DCIMG");`?

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +    RandomAccessInputStream stream = new RandomAccessInputStream(uniqueFiles[zp]);
The stream should be opened and used in a try-with-resources, which means the explicit call to `stream.close()` isn't needed. https://github.com/ome/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/MicroCTReader.java#L148 is one similar example of this pattern.

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +        stream.skip(byteFactor*x);
Here and in lines 124-125, it would be a good idea to combine the seek and skip into a single seek call if possible. Reducing the number of seeks/skips is a known way to improve read performance in general.

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +      byteFactor = 1;
It's not necessary to store the number of bytes per pixel separately. This can be retrieved from the pixel type using `FormatTools.getBytesPerPixel(getPixelType())`.

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +    }
Logging or throwing `FormatException` if an unexpected pixel type is found would be useful.

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +    if (!ext.equals("dcimg")) {
`checkSuffix(file, "dcimg")` (inherited from `FormatHandler`) could be used here instead.

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +
The `close(boolean)` method should be overriden here to reset all fields. https://github.com/ome/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/MicroCTReader.java#L126 is an example.

2024-12-09 17:01 UTC, melissalinkert commented on components/formats-gpl/src/loci/formats/in/DCIMGReader.java
> +    RandomAccessInputStream stream = new RandomAccessInputStream(file);
As in `openBytes` above, this stream should be opened using a try-with-resources.

2024-12-10 10:52 UTC, zacsimile commented
Thanks so much for the feedback! Addressed.

2024-12-17 21:42 UTC, melissalinkert approved these changes
https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-repo/293/ continues to pass with this pull request included, and the last set of changes looks good to me.

Propose to get this in for 8.1.0, but will hold off on merging until the new year in case any final comments.

2025-01-07 09:07 UTC, sbesson commented
Only last question while re-reading the code changes: can I double check the reader is expected to be added to `formats-gpl` - the other option being `formats-bsd` ?

2025-01-07 09:28 UTC, zacsimile commented
One of the codes I based this off of is licensed under GPL-3.0 and the other is MIT. I went more permissive. I didn't explicitly copy code, since it was all Python, so there might be some flexibility here (although I'm not sure, I'm still confused by these licenses). Is there a reason to prefer BSD in this case?

2025-01-07 09:45 UTC, sbesson commented
>  Is there a reason to prefer BSD in this case?

Nothing specific from my side. Just wanted to make sure the licensing aspect had been discussed and decided on your side rather than copy-n-pasted from other reader examples. Relicensing a piece of code after it has been released is doable but also additional work so better to have things sorted before merging.

2025-01-13 15:38 UTC, merged

2025-01-13 15:39 UTC, melissalinkert commented
This is now merged, so will be released in Bio-Formats 8.1.0. Thanks again, @zacsimile!